import Link from "next/link";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Footer from "@/component/Footer";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "CropiGo Ai assistant for farmer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <div id="fixed_nav">
            <div id="navbar" className="container">
              <div className="navLogo">
                <Link href={"/"}>Cropigo</Link>
              </div>
              <ul className="navList">
                <li>
                  <Link href={"/"}>Home</Link>
                </li>
                <li>
                  <Link href={"/about"}>About</Link>
                </li>
                <li>
                  <Link href={"/crop"}>Crop</Link>
                </li>
                <li>
                  <Link href={"/disease"}>Disease</Link>
                </li>
                <li>
                  <Link href={"/downloadapp"}>Download App</Link>
                </li>
              </ul>
            </div>
          </div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
